name: Update version number

on:
  push:
    branches:
      - mustafa

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update version number
        run: |
          # Extract version number from file
          VERSION=$(grep -oP 'version \K\d+(\.\d+)+' change_log.txt)
          echo "Current version is $VERSION"

          # Parse version number into variables
          IFS='.' read -ra VERSION_ARR <<< "$VERSION"
          MAJOR=${VERSION_ARR[0]}
          MINOR=${VERSION_ARR[1]}
          PATCH=${VERSION_ARR[2]}

          if [ "$MINOR" -ge 9 ]; then
              MINOR=0
              MAJOR=$((MAJOR + 1))
          fi
          
          if [ "$PATCH" -ge 9 ]; then
              PATCH=0
              PATCH=$((PATCH + 1))
          else
            MINOR=$((MINOR + 1))
          fi
          
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "New version is $NEW_VERSION"

          # Replace old version number with new one
          sed -i "s/version $VERSION/version $NEW_VERSION/" change_log.txt
          
          
          # commit changes
          git config --global user.name "saha-bot"
          git config --global user.email "saha@github.com"
          git commit -a -m "Update version number to $NEW_VERSION"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: mustafa
          github_token: ${{ secrets.GITHUB_TOKEN }}
