name: Update version number

on:
  push:
    branches:
      - mustafa

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update version number
        run: |
          # Extract version number from file
          VERSION=$(grep -oP 'version \K\d+(\.\d+)+' change_log.txt)
          echo "Current version is $VERSION"

          # Increment version number
          NEW_VERSION=$(echo $VERSION | awk -F. '{$NF = ($(NF-1)+0 == 10 ? $NF + 1 : $NF);} 1' | sed 's/ /./g')
          echo "New version is $NEW_VERSION"

          # Replace old version number with new one
          sed -i "s/version $VERSION/version $NEW_VERSION/" change_log.txt
      - name: Commit changes
        run: |
          git config --global user.name "saha-bot"
          git config --global user.email "saha@github.com"
          git commit -a -m "Update version number to $version"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: mustafa
          github_token: ${{ secrets.GITHUB_TOKEN }}
