name: Update version number

on:
  push:
    branches:
      - mustafa

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update version number
        run: |
          version=$(date +'%Y.%m.%d') 
          sed -i.bak "s/version .*/version $version/" change_log.txt 
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -a -m "Update version number to $version"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
